spring:
  application:
    name: matchday
  
  profiles:
    active: dev

jwt:
  access-token:
    secret-key: ${JWT_ACCESS_SECRET:matchday-access-secret-key-for-development-use-only-change-in-production}
    expire-time: ${JWT_ACCESS_EXPIRE_TIME:3600000} # 1시간
  refresh-token:
    secret-key: ${JWT_REFRESH_SECRET:matchday-refresh-secret-key-for-development-use-only-change-in-production}
    expire-time: ${JWT_REFRESH_EXPIRE_TIME:1209600000} # 2주